use_frameworks!

platform :ios, '9.0'

target 'CircleProgressView_Example' do
  pod 'CircleProgressView', :path => '../'

  target 'CircleProgressView_Tests' do
    inherit! :search_paths

    
  end
end
